# Generated by Django 3.1.6 on 2021-02-13 13:34

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210213_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_editorjs.fields.EditorJsField(verbose_name='Content'),
        ),
    ]
